export default {
  root: {
    backgroundColor: 'white',
    border: '1px solid black',
    borderRadius: '5px',
    padding: '0.5rem',
    position: 'relative',
    overflow: 'hidden',
    cursor: 'pointer',
    '&:hover svg': {
      opacity: '1',
    },
  },
  colors: {
    backgroundColor: '#dae1e4',
    height: '150px',
    width: '100%',
    borderRadius: '5px',
    overflow: 'hidden',
    display: 'flex',
    flexWrap: 'wrap',
    flexDirection: 'flex-start',
  },
  title: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    margin: '0',
    color: 'black',
    paddingTop: '0.5rem',
    fontSize: '1rem',
    position: 'relative',
  },
  emoji: {
    marginLeft: '0.5rem',
    fontSize: '1.5rem',
  },
  miniColor: {
    flexBasis: '20%',
    flexGrow: '1',
  },
  delete: {},
  deleteIcon: {
    position: 'absolute',
    top: '0',
    right: '0',
    color: 'white',
    padding: '10px',
    zIndex: '10',
    margin: '2px',
    backgroundColor: '#eb3d30',
    opacity: 0,
    '&:hover': {
      transform: 'scale(1.1)',
    },
  },
};
